language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- python3 -m unittest discover -s locstats/tests
deploy:
  provider: pypi
  user: "__token__"
  distributions: sdist bdist_wheel
  password:
    secure: n7HQIUXqKghk7mZvHCP+z5BKSnPDDFhAOKPXdWCRh1dw5Ot9T/72PoFSnMi8tY5fEGkedgVHHd1a7/Nsp9P2OnalO3kPfz3swv5OEumu9SJLLwcc9lSrmPCejRjQpnmkm8yByUh9ueCAtpq/RKxqHj4z9D8gV1j9HGbkQvZn2BJfC1tuKn5H/YuceDpUsjYQcbn50G8kJQj3d849kul3qaTrXLjbe0shvr5jw2hSLTFONa52KplR+5VHJFINB3Su356k9uQpF/X0LNPGN5TMyTJY9yuAPlybGJa+6/R8BFJa/4iEzxjWSWbf27v1Fqsc7vZ3rFY+lmGn1NcYuOzsG/843DSy2A2SBFU4JI7vPWbhCXKHB54YKGPyFqSv0+0xGQ1WKywegHbnpJytDm5sQWbz+qk97H7bVmFLUOElWfs9w/uJ2I1UDqhUiip6/wFq7vjRAy4jOHn+VYnSwPcCTXDY4Wcep9woqnweKsAzH0+ecGfKSkKwVXPmlDxYmflvdITvRe6OQR5zc6ysYWMjrxr5kKAW6Ml79DuGZPZhOWoXIFlTwvedr8t7hVuQ0agTtvE2ZUP8Kk6HkcOOQqj2cdlwWgoOVmEVQSwxCfKC84JT1rR0Keuzcc2MDCZA50HXMUifr/WvHBLjBM8oYsUiOZks263qX3RGpr77mKJv/Gw=
  skip_existing: true
  on:
    tags: true
